typography_spectrum: 0.48219267558306456
color:
  brandStrength: 0.7236337752547115
  lightness: 0.23225578083656728
  saturation: 0.7392125343903899
  rhythmicContrast: 0.056903738994151354
  brandColors:
    - '#105B63'
    - '#FFFAD5'
    - '#FFD34E'
    - '#DB9E36'
    - '#BD4932'
layout_spectrum: 0.21478093951009214
author:
  name: Andrew Crosby
  email: andrewncrosby@gmail.com
name: LaTetedelaCuvee
navigation:
  - name: Trade
    id: cb4ac8f9-4ee0-4a8b-9a9c-0a8a010c2d8b
    type: content
title: La Tete de la Cuvee
description: best from first press
